[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate-tls"
version = "0.18.0"

[dependencies]
once_cell = { version = "1.17", default-features = false }
poem = { version = "3.1", features = ["rustls"], default-features = false }
poem-openapi.workspace = true
rustls-native-certs = { version = "0.8", default-features = false }
rustls-pki-types.workspace = true
rustls.workspace = true
sea-orm.workspace = true
serde_json.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio-rustls.workspace = true
tokio.workspace = true
tracing.workspace = true
webpki = { version = "0.22", default-features = false }
x509-parser = "0.17.0"
