[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate-web"
version = "0.20.0"

[dependencies]
serde.workspace = true
rust-embed = { version = "8.3", default-features = false }
serde_json.workspace = true
thiserror.workspace = true
