[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate-sso"
version = "0.18.0"

[dependencies]
bytes.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
openidconnect = { version = "4.0", default-features = false, features = [
    "reqwest",
    "accept-string-booleans",
] }
serde.workspace = true
serde_json.workspace = true
once_cell = { version = "1.17", default-features = false }
jsonwebtoken = { version = "9", default-features = false, features = ["use_pem"] }
data-encoding.workspace = true
futures.workspace = true
schemars.workspace = true
