[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate-sso"
version = "0.6.1"

[dependencies]
bytes = "1.2"
thiserror = "1.0"
tokio = { version = "1.20", features = ["tracing", "macros"] }
tracing = "0.1"
openidconnect = { version = "2.3", features = ["reqwest", "rustls-tls"] }
serde = "1.0"
serde_json = "1.0"
once_cell = "1.14"
