[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate-core"
version = "0.20.2"

[dependencies]
warpgate-common = { version = "*", path = "../warpgate-common" }
warpgate-db-entities = { version = "*", path = "../warpgate-db-entities" }
warpgate-db-migrations = { version = "*", path = "../warpgate-db-migrations" }
warpgate-ldap = { version = "*", path = "../warpgate-ldap" }

anyhow = { version = "1.0", features = ["std"] }
argon2 = "0.5"
async-trait = "0.1"
bytes.workspace = true
chrono = { version = "0.4", default-features = false, features = ["serde"] }
data-encoding.workspace = true
dialoguer.workspace = true
enum_dispatch.workspace = true
humantime-serde = "1.1"
futures.workspace = true
ldap3.workspace = true
once_cell = "1.17"
packet = "0.1"
password-hash.workspace = true
poem.workspace = true
poem-openapi.workspace = true
rand.workspace = true
rand_chacha.workspace = true
rand_core.workspace = true
russh.workspace = true
sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
totp-rs = { version = "5.0", features = ["otpauth"], default-features = false }
tracing.workspace = true
tracing-core = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false }
url = { version = "2.2", default-features = false }
uuid = { version = "1.3", features = ["v4", "serde"], default-features = false }
warpgate-sso = { version = "*", path = "../warpgate-sso", default-features = false }
rustls.workspace = true
webpki = { version = "0.22", default-features = false }
governor.workspace = true

[features]
postgres = ["sea-orm/sqlx-postgres"]
mysql = ["sea-orm/sqlx-mysql"]
sqlite = ["sea-orm/sqlx-sqlite"]
