[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate"
version = "0.14.0"

[dependencies]
ansi_term = "0.12"
anyhow = { version = "1.0", features = ["backtrace"] }
async-trait = "0.1"
bytes.workspace = true
clap = { version = "4.0", features = ["derive"] }
config = { version = "0.15", features = ["yaml"], default-features = false }
console = { version = "0.15", default-features = false }
console-subscriber = { version = "0.4", optional = true }
data-encoding.workspace = true
dialoguer.workspace = true
enum_dispatch.workspace = true
futures.workspace = true
notify = "8.0"
rcgen = { version = "0.13", features = ["zeroize"] }
rustls.workspace = true
serde_json.workspace = true
serde_yaml = "0.9"
sea-orm.workspace = true
time = "0.3"
tokio = { version = "1.20", features = ["tracing", "signal", "macros"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "local-time",
] }
uuid = "1.3"
warpgate-admin = { version = "*", path = "../warpgate-admin" }
warpgate-common = { version = "*", path = "../warpgate-common" }
warpgate-core = { version = "*", path = "../warpgate-core" }
warpgate-db-entities = { version = "*", path = "../warpgate-db-entities" }
warpgate-protocol-http = { version = "*", path = "../warpgate-protocol-http" }
warpgate-protocol-mysql = { version = "*", path = "../warpgate-protocol-mysql" }
warpgate-protocol-postgres = { version = "*", path = "../warpgate-protocol-postgres" }
warpgate-protocol-ssh = { version = "*", path = "../warpgate-protocol-ssh" }
schemars.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
sd-notify = "0.4"

[features]
default = ["sqlite"]
tokio-console = ["dep:console-subscriber", "tokio/tracing"]
postgres = ["warpgate-core/postgres"]
mysql = ["warpgate-core/mysql"]
sqlite = ["warpgate-core/sqlite"]
