[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate"
version = "0.19.1"

[dependencies]
ansi_term = { version = "0.12", default-features = false }
anyhow = { version = "1.0", features = ["backtrace"], default-features = false }
async-trait = { version = "0.1", default-features = false }
bytes.workspace = true
clap = { version = "4.0", features = ["derive"], default-features = false }
config = { version = "0.15", features = ["yaml"], default-features = false }
console = { version = "0.15", default-features = false }
console-subscriber = { version = "0.4", optional = true, default-features = false }
data-encoding.workspace = true
dialoguer.workspace = true
enum_dispatch.workspace = true
futures.workspace = true
notify = { version = "8.0", default-features = false, features = ["fsevent-sys"] }
rcgen.workspace = true
reqwest.workspace = true
rustls.workspace = true
serde_json.workspace = true
serde_yaml = { version = "0.9", default-features = false }
sea-orm.workspace = true
time = { version = "0.3", default-features = false }
tokio.workspace = true
tracing.workspace = true
tracing-log = { version = "0.2" }
tracing-subscriber = { version = "0.3", features = [
    "ansi",
    "env-filter",
    "local-time",
], default-features = false }
uuid = { version = "1.3", default-features = false }
warpgate-admin = { version = "*", path = "../warpgate-admin" }
warpgate-common = { version = "*", path = "../warpgate-common" }
warpgate-core = { version = "*", path = "../warpgate-core" }
warpgate-db-entities = { version = "*", path = "../warpgate-db-entities" }
warpgate-protocol-http = { version = "*", path = "../warpgate-protocol-http" }
warpgate-protocol-mysql = { version = "*", path = "../warpgate-protocol-mysql" }
warpgate-protocol-postgres = { version = "*", path = "../warpgate-protocol-postgres" }
warpgate-protocol-ssh = { version = "*", path = "../warpgate-protocol-ssh" }
warpgate-tls = { version = "*", path = "../warpgate-tls" }
schemars.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
sd-notify = { version = "0.4", default-features = false }

[features]
default = ["sqlite"]
tokio-console = ["dep:console-subscriber", "tokio/tracing"]
postgres = ["warpgate-core/postgres"]
mysql = ["warpgate-core/mysql"]
sqlite = ["warpgate-core/sqlite"]
