[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate"
version = "0.7.1"

[dependencies]
ansi_term = "0.12"
anyhow = { version = "1.0", features = ["backtrace"] }
async-trait = "0.1"
atty = "0.2"
bytes = "1.4"
clap = { version = "3.2", features = ["derive"] }
config = { version = "0.13", features = ["yaml"], default_features = false }
console = { version = "0.15", default_features = false }
console-subscriber = { version = "0.1", optional = true }
data-encoding = "2.3"
dialoguer = "0.10"
futures = "0.3"
notify = "^5.0.0"
rcgen = { version = "0.10", features = ["zeroize"] }
serde_json = "1.0"
serde_yaml = "0.8.23"
sea-orm = { version = "0.10.6", default-features = false }
time = "0.3"
tokio = { version = "1.20", features = ["tracing", "signal", "macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "local-time",
] }
uuid = "1.2"
warpgate-admin = { version = "*", path = "../warpgate-admin" }
warpgate-common = { version = "*", path = "../warpgate-common" }
warpgate-core = { version = "*", path = "../warpgate-core" }
warpgate-db-entities = { version = "*", path = "../warpgate-db-entities" }
warpgate-protocol-http = { version = "*", path = "../warpgate-protocol-http" }
warpgate-protocol-mysql = { version = "*", path = "../warpgate-protocol-mysql" }
warpgate-protocol-ssh = { version = "*", path = "../warpgate-protocol-ssh" }

[target.'cfg(target_os = "linux")'.dependencies]
sd-notify = "0.4"

[features]
default = ["sqlite"]
tokio-console = ["dep:console-subscriber", "tokio/tracing"]
postgres = ["warpgate-core/postgres"]
mysql = ["warpgate-core/mysql"]
sqlite = ["warpgate-core/sqlite"]
